(function () {
  const groups = {
    primordial: {
      label: "원초신",
      color: "#4b5563",
      description: "세계가 형성되기 전후에 등장하는 근원적 존재들",
    },
    titan: {
      label: "티탄",
      color: "#9a6b2f",
      description: "우라노스와 가이아의 자식 세대",
    },
    olympian: {
      label: "올림포스",
      color: "#2563eb",
      description: "크로노스 이후 세계의 중심이 되는 올림포스 신들",
    },
    god: {
      label: "신",
      color: "#0f766e",
      description: "올림포스 주신은 아니지만 주요 계보에 포함되는 신들",
    },
    hero: {
      label: "영웅",
      color: "#b91c1c",
      description: "신과 인간의 결합에서 태어난 주요 영웅",
    },
    mortal: {
      label: "인간",
      color: "#6b7280",
      description: "주요 영웅의 부모로 계보에 필요한 인간 인물",
    },
  };

  const gods = [
    {
      id: "chaos",
      name: "카오스",
      englishName: "Chaos",
      greekName: "Khaos",
      group: "primordial",
      generation: 0,
      parents: [],
      partners: [],
      domain: ["공허", "기원"],
      summary: "그리스 신화에서 세계가 시작되기 전의 원초적 공허.",
    },
    {
      id: "gaia",
      name: "가이아",
      englishName: "Gaia",
      greekName: "Gaia",
      group: "primordial",
      generation: 1,
      parents: ["chaos"],
      partners: ["uranus", "pontus", "tartarus"],
      domain: ["대지"],
      summary: "대지의 여신. 우라노스와 결합해 티탄 세대를 낳는다.",
    },
    {
      id: "tartarus",
      name: "타르타로스",
      englishName: "Tartarus",
      greekName: "Tartaros",
      group: "primordial",
      generation: 1,
      parents: ["chaos"],
      partners: ["gaia"],
      domain: ["심연", "감옥"],
      summary: "지하 깊은 심연이자 신적 존재.",
    },
    {
      id: "eros",
      name: "에로스",
      englishName: "Eros",
      greekName: "Eros",
      group: "primordial",
      generation: 1,
      parents: ["chaos"],
      partners: [],
      domain: ["사랑", "생성의 힘"],
      summary: "초기 전승에서 세계의 생성을 가능하게 하는 사랑의 힘.",
    },
    {
      id: "erebus",
      name: "에레보스",
      englishName: "Erebus",
      greekName: "Erebos",
      group: "primordial",
      generation: 1,
      parents: ["chaos"],
      partners: ["nyx"],
      domain: ["어둠"],
      summary: "지하와 세계 사이의 어둠을 상징하는 원초신.",
    },
    {
      id: "nyx",
      name: "닉스",
      englishName: "Nyx",
      greekName: "Nyx",
      group: "primordial",
      generation: 1,
      parents: ["chaos"],
      partners: ["erebus"],
      domain: ["밤"],
      summary: "밤의 여신. 여러 추상적 신격의 어머니로 전해진다.",
    },
    {
      id: "aether",
      name: "아이테르",
      englishName: "Aether",
      greekName: "Aither",
      group: "primordial",
      generation: 2,
      parents: ["erebus", "nyx"],
      partners: [],
      domain: ["상층의 빛", "맑은 공기"],
      summary: "신들이 숨 쉬는 밝고 높은 공기의 신격.",
    },
    {
      id: "hemera",
      name: "헤메라",
      englishName: "Hemera",
      greekName: "Hemera",
      group: "primordial",
      generation: 2,
      parents: ["erebus", "nyx"],
      partners: [],
      domain: ["낮"],
      summary: "낮의 여신.",
    },
    {
      id: "uranus",
      name: "우라노스",
      englishName: "Uranus",
      greekName: "Ouranos",
      group: "primordial",
      generation: 2,
      parents: ["gaia"],
      partners: ["gaia"],
      domain: ["하늘"],
      summary: "하늘의 신. 가이아와 함께 티탄, 키클롭스, 헤카톤케이레스의 부모가 된다.",
    },
    {
      id: "pontus",
      name: "폰토스",
      englishName: "Pontus",
      greekName: "Pontos",
      group: "primordial",
      generation: 2,
      parents: ["gaia"],
      partners: ["gaia"],
      domain: ["바다"],
      summary: "바다의 원초신.",
    },
    {
      id: "ourea",
      name: "우레아",
      englishName: "Ourea",
      greekName: "Ourea",
      group: "primordial",
      generation: 2,
      parents: ["gaia"],
      partners: [],
      domain: ["산"],
      summary: "산들의 신격. 보통 집합적 존재로 다뤄진다.",
    },

    {
      id: "oceanus",
      name: "오케아노스",
      englishName: "Oceanus",
      greekName: "Okeanos",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["tethys"],
      domain: ["대양"],
      summary: "세계를 둘러싼 대양의 티탄.",
    },
    {
      id: "tethys",
      name: "테티스",
      englishName: "Tethys",
      greekName: "Tethys",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["oceanus"],
      domain: ["강", "샘"],
      summary: "오케아노스와 함께 강과 물의 신격들을 낳은 티탄.",
    },
    {
      id: "hyperion",
      name: "히페리온",
      englishName: "Hyperion",
      greekName: "Hyperion",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["theia"],
      domain: ["천상의 빛"],
      summary: "해, 달, 새벽 신격의 아버지.",
    },
    {
      id: "theia",
      name: "테이아",
      englishName: "Theia",
      greekName: "Theia",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["hyperion"],
      domain: ["시야", "광휘"],
      summary: "히페리온의 배우자이며 헬리오스, 셀레네, 에오스의 어머니.",
    },
    {
      id: "coeus",
      name: "코이오스",
      englishName: "Coeus",
      greekName: "Koios",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["phoebe"],
      domain: ["지성", "축"],
      summary: "레토와 아스테리아의 아버지.",
    },
    {
      id: "phoebe",
      name: "포이베",
      englishName: "Phoebe",
      greekName: "Phoibe",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["coeus"],
      domain: ["예언", "밝음"],
      summary: "코이오스의 배우자이며 레토와 아스테리아의 어머니.",
    },
    {
      id: "crius",
      name: "크리오스",
      englishName: "Crius",
      greekName: "Krios",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: [],
      domain: ["별자리"],
      summary: "티탄 세대의 일원.",
    },
    {
      id: "iapetus",
      name: "이아페토스",
      englishName: "Iapetus",
      greekName: "Iapetos",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["clymene"],
      domain: ["인간의 조상 계열"],
      summary: "아틀라스, 프로메테우스, 에피메테우스의 아버지.",
    },
    {
      id: "themis",
      name: "테미스",
      englishName: "Themis",
      greekName: "Themis",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["zeus"],
      domain: ["질서", "법"],
      summary: "질서와 정의의 티탄 여신.",
    },
    {
      id: "mnemosyne",
      name: "므네모시네",
      englishName: "Mnemosyne",
      greekName: "Mnemosyne",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["zeus"],
      domain: ["기억"],
      summary: "기억의 여신. 제우스와의 사이에서 무사이 아홉 자매를 낳는다.",
    },
    {
      id: "cronus",
      name: "크로노스",
      englishName: "Cronus",
      greekName: "Kronos",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["rhea"],
      domain: ["시간", "티탄 왕권"],
      summary: "우라노스를 몰아내고 티탄의 왕이 되었으나 제우스에게 패한다.",
    },
    {
      id: "rhea",
      name: "레아",
      englishName: "Rhea",
      greekName: "Rhea",
      group: "titan",
      generation: 3,
      parents: ["gaia", "uranus"],
      partners: ["cronus"],
      domain: ["모성"],
      summary: "크로노스의 배우자이며 올림포스 주신 세대의 어머니.",
    },

    {
      id: "helios",
      name: "헬리오스",
      englishName: "Helios",
      greekName: "Helios",
      group: "god",
      generation: 4,
      parents: ["hyperion", "theia"],
      partners: [],
      domain: ["태양"],
      summary: "태양을 몰고 하늘을 지나가는 신.",
    },
    {
      id: "selene",
      name: "셀레네",
      englishName: "Selene",
      greekName: "Selene",
      group: "god",
      generation: 4,
      parents: ["hyperion", "theia"],
      partners: [],
      domain: ["달"],
      summary: "달의 여신.",
    },
    {
      id: "eos",
      name: "에오스",
      englishName: "Eos",
      greekName: "Eos",
      group: "god",
      generation: 4,
      parents: ["hyperion", "theia"],
      partners: [],
      domain: ["새벽"],
      summary: "새벽의 여신.",
    },
    {
      id: "leto",
      name: "레토",
      englishName: "Leto",
      greekName: "Leto",
      group: "god",
      generation: 4,
      parents: ["coeus", "phoebe"],
      partners: ["zeus"],
      domain: ["모성"],
      summary: "아폴론과 아르테미스의 어머니.",
    },
    {
      id: "asteria",
      name: "아스테리아",
      englishName: "Asteria",
      greekName: "Asteria",
      group: "god",
      generation: 4,
      parents: ["coeus", "phoebe"],
      partners: [],
      domain: ["별", "밤의 예언"],
      summary: "레토의 자매.",
    },
    {
      id: "clymene",
      name: "클리메네",
      englishName: "Clymene",
      greekName: "Klymene",
      group: "god",
      generation: 4,
      parents: ["oceanus", "tethys"],
      partners: ["iapetus"],
      domain: ["오케아니스"],
      summary: "전승에 따라 이아페토스 자식들의 어머니로 등장한다.",
    },
    {
      id: "metis",
      name: "메티스",
      englishName: "Metis",
      greekName: "Metis",
      group: "god",
      generation: 4,
      parents: ["oceanus", "tethys"],
      partners: ["zeus"],
      domain: ["지혜", "책략"],
      summary: "제우스의 첫 배우자. 아테나의 어머니.",
    },
    {
      id: "atlas",
      name: "아틀라스",
      englishName: "Atlas",
      greekName: "Atlas",
      group: "titan",
      generation: 4,
      parents: ["iapetus", "clymene"],
      partners: [],
      domain: ["하늘을 떠받침"],
      summary: "티타노마키아 이후 하늘을 떠받치는 벌을 받는다.",
    },
    {
      id: "prometheus",
      name: "프로메테우스",
      englishName: "Prometheus",
      greekName: "Prometheus",
      group: "titan",
      generation: 4,
      parents: ["iapetus", "clymene"],
      partners: [],
      domain: ["예지", "불"],
      summary: "인간에게 불을 전해 준 티탄.",
    },
    {
      id: "epimetheus",
      name: "에피메테우스",
      englishName: "Epimetheus",
      greekName: "Epimetheus",
      group: "titan",
      generation: 4,
      parents: ["iapetus", "clymene"],
      partners: ["pandora"],
      domain: ["사후 판단"],
      summary: "프로메테우스의 형제. 판도라와 연결된다.",
    },

    {
      id: "hestia",
      name: "헤스티아",
      englishName: "Hestia",
      greekName: "Hestia",
      group: "olympian",
      generation: 4,
      parents: ["cronus", "rhea"],
      partners: [],
      domain: ["화로", "가정"],
      summary: "가정과 화로의 여신.",
    },
    {
      id: "demeter",
      name: "데메테르",
      englishName: "Demeter",
      greekName: "Demeter",
      group: "olympian",
      generation: 4,
      parents: ["cronus", "rhea"],
      partners: ["zeus"],
      domain: ["농경", "곡물"],
      summary: "농경의 여신. 페르세포네의 어머니.",
    },
    {
      id: "hera",
      name: "헤라",
      englishName: "Hera",
      greekName: "Hera",
      group: "olympian",
      generation: 4,
      parents: ["cronus", "rhea"],
      partners: ["zeus"],
      domain: ["결혼", "왕권"],
      summary: "제우스의 배우자이며 신들의 여왕.",
    },
    {
      id: "hades",
      name: "하데스",
      englishName: "Hades",
      greekName: "Hades",
      group: "olympian",
      generation: 4,
      parents: ["cronus", "rhea"],
      partners: ["persephone"],
      domain: ["저승"],
      summary: "저승의 신. 올림포스 12신에는 보통 포함되지 않는다.",
    },
    {
      id: "poseidon",
      name: "포세이돈",
      englishName: "Poseidon",
      greekName: "Poseidon",
      group: "olympian",
      generation: 4,
      parents: ["cronus", "rhea"],
      partners: ["amphitrite"],
      domain: ["바다", "지진", "말"],
      summary: "바다와 지진의 신.",
    },
    {
      id: "zeus",
      name: "제우스",
      englishName: "Zeus",
      greekName: "Zeus",
      group: "olympian",
      generation: 4,
      parents: ["cronus", "rhea"],
      partners: ["hera", "metis", "leto", "demeter", "maia", "semele", "danae", "alcmene", "themis", "mnemosyne"],
      domain: ["하늘", "번개", "왕권"],
      summary: "크로노스를 몰아내고 올림포스 질서를 세운 신들의 왕.",
    },

    {
      id: "athena",
      name: "아테나",
      englishName: "Athena",
      greekName: "Athena",
      group: "olympian",
      generation: 5,
      parents: ["zeus", "metis"],
      partners: [],
      domain: ["지혜", "전략", "수공업"],
      summary: "제우스의 머리에서 태어난 지혜와 전략의 여신.",
    },
    {
      id: "apollo",
      name: "아폴론",
      englishName: "Apollo",
      greekName: "Apollon",
      group: "olympian",
      generation: 5,
      parents: ["zeus", "leto"],
      partners: [],
      domain: ["예언", "음악", "궁술", "태양"],
      summary: "델포이 예언과 음악, 궁술의 신.",
    },
    {
      id: "artemis",
      name: "아르테미스",
      englishName: "Artemis",
      greekName: "Artemis",
      group: "olympian",
      generation: 5,
      parents: ["zeus", "leto"],
      partners: [],
      domain: ["사냥", "달", "야생"],
      summary: "사냥과 야생의 여신.",
    },
    {
      id: "ares",
      name: "아레스",
      englishName: "Ares",
      greekName: "Ares",
      group: "olympian",
      generation: 5,
      parents: ["zeus", "hera"],
      partners: ["aphrodite"],
      domain: ["전쟁"],
      summary: "전쟁의 폭력성과 충돌을 상징하는 신.",
    },
    {
      id: "hebe",
      name: "헤베",
      englishName: "Hebe",
      greekName: "Hebe",
      group: "god",
      generation: 5,
      parents: ["zeus", "hera"],
      partners: ["heracles"],
      domain: ["청춘"],
      summary: "젊음의 여신.",
    },
    {
      id: "eileithyia",
      name: "에일레이티이아",
      englishName: "Eileithyia",
      greekName: "Eileithyia",
      group: "god",
      generation: 5,
      parents: ["zeus", "hera"],
      partners: [],
      domain: ["출산"],
      summary: "출산을 관장하는 여신.",
    },
    {
      id: "hephaestus",
      name: "헤파이스토스",
      englishName: "Hephaestus",
      greekName: "Hephaistos",
      group: "olympian",
      generation: 5,
      parents: ["hera"],
      partners: ["aphrodite"],
      domain: ["대장장이", "불", "공예"],
      summary: "불과 대장장이의 신. 출생 전승은 여러 갈래가 있다.",
      note: "어떤 전승에서는 제우스와 헤라의 아들로도 나온다.",
    },
    {
      id: "persephone",
      name: "페르세포네",
      englishName: "Persephone",
      greekName: "Persephone",
      group: "god",
      generation: 5,
      parents: ["zeus", "demeter"],
      partners: ["hades"],
      domain: ["봄", "저승의 여왕"],
      summary: "데메테르의 딸이며 하데스의 배우자.",
    },
    {
      id: "hermes",
      name: "헤르메스",
      englishName: "Hermes",
      greekName: "Hermes",
      group: "olympian",
      generation: 5,
      parents: ["zeus", "maia"],
      partners: [],
      domain: ["전령", "상업", "여행", "도둑"],
      summary: "신들의 전령.",
    },
    {
      id: "dionysus",
      name: "디오니소스",
      englishName: "Dionysus",
      greekName: "Dionysos",
      group: "olympian",
      generation: 5,
      parents: ["zeus", "semele"],
      partners: ["ariadne"],
      domain: ["포도주", "광희", "연극"],
      summary: "포도주와 축제의 신. 후대에는 12신에 포함되기도 한다.",
    },
    {
      id: "aphrodite",
      name: "아프로디테",
      englishName: "Aphrodite",
      greekName: "Aphrodite",
      group: "olympian",
      generation: 5,
      parents: ["uranus"],
      partners: ["hephaestus", "ares"],
      domain: ["사랑", "미"],
      summary: "사랑과 미의 여신.",
      note: "헤시오도스 전승에서는 우라노스에서 비롯되고, 다른 전승에서는 제우스와 디오네의 딸로 나온다.",
    },

    {
      id: "maia",
      name: "마이아",
      englishName: "Maia",
      greekName: "Maia",
      group: "god",
      generation: 5,
      parents: ["atlas"],
      partners: ["zeus"],
      domain: ["플레이아데스"],
      summary: "아틀라스의 딸 중 하나이며 헤르메스의 어머니.",
    },
    {
      id: "semele",
      name: "세멜레",
      englishName: "Semele",
      greekName: "Semele",
      group: "mortal",
      generation: 5,
      parents: [],
      partners: ["zeus"],
      domain: ["테베 왕가"],
      summary: "디오니소스의 인간 어머니.",
    },
    {
      id: "danae",
      name: "다나에",
      englishName: "Danae",
      greekName: "Danae",
      group: "mortal",
      generation: 5,
      parents: [],
      partners: ["zeus"],
      domain: ["아르고스 왕가"],
      summary: "페르세우스의 어머니.",
    },
    {
      id: "alcmene",
      name: "알크메네",
      englishName: "Alcmene",
      greekName: "Alkmene",
      group: "mortal",
      generation: 5,
      parents: [],
      partners: ["zeus"],
      domain: ["테베 왕가"],
      summary: "헤라클레스의 어머니.",
    },
    {
      id: "amphitrite",
      name: "암피트리테",
      englishName: "Amphitrite",
      greekName: "Amphitrite",
      group: "god",
      generation: 5,
      parents: [],
      partners: ["poseidon"],
      domain: ["바다의 여왕"],
      summary: "포세이돈의 배우자.",
    },
    {
      id: "ariadne",
      name: "아리아드네",
      englishName: "Ariadne",
      greekName: "Ariadne",
      group: "mortal",
      generation: 6,
      parents: [],
      partners: ["dionysus"],
      domain: ["크레타 왕가"],
      summary: "테세우스 신화와 디오니소스 전승에 등장하는 인물.",
    },
    {
      id: "pandora",
      name: "판도라",
      englishName: "Pandora",
      greekName: "Pandora",
      group: "mortal",
      generation: 5,
      parents: [],
      partners: ["epimetheus"],
      domain: ["첫 여성"],
      summary: "신들이 만든 첫 여성으로 전해진다.",
    },
    {
      id: "perseus",
      name: "페르세우스",
      englishName: "Perseus",
      greekName: "Perseus",
      group: "hero",
      generation: 6,
      parents: ["zeus", "danae"],
      partners: [],
      domain: ["영웅"],
      summary: "메두사를 처치한 영웅.",
    },
    {
      id: "heracles",
      name: "헤라클레스",
      englishName: "Heracles",
      greekName: "Herakles",
      group: "hero",
      generation: 6,
      parents: ["zeus", "alcmene"],
      partners: ["hebe"],
      domain: ["영웅", "힘"],
      summary: "열두 과업으로 유명한 영웅. 사후 신격화된다.",
    },
  ];

  const relationNotes = [
    {
      id: "aphrodite-origin",
      title: "아프로디테의 출생",
      text: "헤시오도스 계통에서는 우라노스에서 비롯되지만, 호메로스 계통에서는 제우스와 디오네의 딸로 나온다.",
      relatedIds: ["aphrodite", "uranus", "zeus"],
    },
    {
      id: "hephaestus-origin",
      title: "헤파이스토스의 출생",
      text: "헤라가 홀로 낳았다는 전승과 제우스와 헤라의 아들이라는 전승이 모두 있다.",
      relatedIds: ["hephaestus", "hera", "zeus"],
    },
    {
      id: "olympian-twelve",
      title: "올림포스 12신",
      text: "헤스티아, 하데스, 디오니소스의 포함 여부는 목록마다 다르다. 이 데이터에서는 세 신 모두 표시하고 앱 화면에서 필터로 조정할 수 있게 둔다.",
      relatedIds: ["hestia", "hades", "dionysus"],
    },
  ];

  window.GREEK_MYTH_GODS = {
    meta: {
      title: "그리스 신화 계보",
      version: "0.1.0",
      language: "ko",
      basis: "초기 화면 구성을 위한 핵심 계보 데이터. 전승이 갈리는 항목은 relationNotes에 따로 표시했다.",
    },
    groups,
    gods,
    relationNotes,
  };
})();
